CREATE DATABASE NewCustomers;
USE NewCustomers;
create table Customers (CUST_ID CHAR(3), CUST_FIRST_NAME CHAR(10), CUST_LAST_NAME CHAR(10), ADDRESS CHAR(30), CITY CHAR(15), STATE CHAR(2), ZIP CHAR(5), EMAIL_ADDRESS CHAR(20), PHONE_NUMBER VARCHAR(16));