CREATE DATABASE LCC;

USE LCC;

Create Table STUDENTS (STU_ID VARCHAR(8), STU_FIRST_NAME VARCHAR(32), STU_LAST_NAME VARCHAR(32), ADDRESS VARCHAR(64), CITY VARCHAR(32), STATE CHAR(2), ZIP CHAR(5), MAJOR VARCHAR(32), EMAIL_ADDRESS VARCHAR(64), PHONE_NUMBER CHAR(7));

INSERT INTO STUDENTS (STU_ID , STU_FIRST_NAME , STU_LAST_NAME , ADDRESS , CITY , STATE , ZIP , MAJOR , EMAIL_ADDRESS , PHONE_NUMBER ) VALUES ("01", "Jacob", "Archambault", "2630 Whitehall Ter", "Louisville", "KY", "40220", "Programming", "a@gmail.com", "5551234");

INSERT INTO STUDENTS (STU_ID , STU_FIRST_NAME , STU_LAST_NAME , ADDRESS , CITY , STATE , ZIP , MAJOR , EMAIL_ADDRESS , PHONE_NUMBER ) VALUES 
("02", "Foo", "Bar", "34 My street", "Louisville", "KY", "12345", "Philosophy", "b@yahoo.com", "5554321");

INSERT INTO STUDENTS (STU_ID , STU_FIRST_NAME , STU_LAST_NAME , ADDRESS , CITY , STATE , ZIP , MAJOR , EMAIL_ADDRESS , PHONE_NUMBER ) VALUES 
("03", "Fred", "Astaire", "22 Dancehall Row", "Bronx", "NY", "10458", "Dance", "Fred@yahoo.com", "5559876");

INSERT INTO STUDENTS (STU_ID , STU_FIRST_NAME , STU_LAST_NAME , ADDRESS , CITY , STATE , ZIP , MAJOR , EMAIL_ADDRESS , PHONE_NUMBER ) VALUES 
("04", "Julia", "Styles", "64 Broadway", "New York", "NY", "10459", "Theater", "Julia@gmail.com", "4839586");

INSERT INTO STUDENTS (STU_ID , STU_FIRST_NAME , STU_LAST_NAME , ADDRESS , CITY , STATE , ZIP , MAJOR , EMAIL_ADDRESS , PHONE_NUMBER ) VALUES 
("05", "Jennifer", "Lawrence", "590 High street", "Louisville", "KY", "40234", "Archery", "jlaw@gmail.com", "2839536");

SELECT * FROM STUDENTS;
